Ingredients
SergioDegas/SoYummyBackend pull request #19
Opened 2023-04-02 19:21 UTC by IhorMelnyk90

2023-04-02 19:32 UTC, po4tovuj requested changes
завтра напишу зауваження

2023-04-03 07:25 UTC, po4tovuj commented on src/controllers/ingredients/getIngredientsList.js
> +module.exports = { getIngredients };
якщо в тебе один метод експортується і більше не планується ( як у нас) то не треба єекспортувати його як об'єкт. module.exports = getIngredients

2023-04-03 07:26 UTC, po4tovuj commented on src/controllers/ingredients/index.js
> +const { getIngredients } = require("./getIngredientsList");
відповідно якщо експортуєш не обєкт то не треба робити деструктурізацію

2023-04-03 18:47 UTC, IhorMelnyk90 commented
Пофіксив зауваження

2023-04-03 18:49 UTC, po4tovuj commented on src/routes/api/ingredients.js
>  const ingredientsCtrl = require("../../controllers/ingredients");
ось тут const {getIngredients} = require("../../controllers/ingredients");

2023-04-03 18:49 UTC, po4tovuj commented on src/routes/api/ingredients.js
> +router.get("/", authenticate, ingredientsCtrl.getIngredients);
а тут просто getIngredients

2023-04-03 18:52 UTC, IhorMelnyk90 commented on src/routes/api/ingredients.js
> +router.get("/", authenticate, ingredientsCtrl.getIngredients);
поправив

2023-04-03 18:53 UTC, merged