Fix/recipes
SergioDegas/SoYummyBackend pull request #20
Opened 2023-04-02 20:33 UTC by SergiiTernytskyi

2023-04-03 10:31 UTC, po4tovuj requested changes

2023-04-03 10:31 UTC, po4tovuj commented on src/controllers/recipes/getCategoryList.js
>  const { categories } = require("../../helpers");
Це не хелперс, це данні. Хелпери мають в чомусь допомогати, щось робити. а тут статичні данні.  я б поклав іх у json файл і звідти просто брав. Але точно не в хелпери

2023-04-03 10:31 UTC, po4tovuj commented on src/controllers/recipes/getRecipesByCategory.js
> +	if (!result || result.length === 0) {
чому якщо жодного рецепту в категорії не знайшло ти повертаєш 400? якщо запит пройшов успішно але жодного рецепту в категорії немає, ти маєш повернути пустий масив, а не 400

2023-04-03 12:41 UTC, SergiiTernytskyi commented on src/service/recipes.js
>  	return await Recipe.findOne({ _id: recipeId });
Так такий метод існує і він нічим не відрізняється від findOne, а пыд капотом mongoose перетворює findById(undefined) в findOne({ _id: null }). Тому не бачу тут принципової різниці, окрім економії кількох символів, на функціонал ніякого впливу немає

2023-04-03 13:30 UTC, SergiiTernytskyi commented on src/controllers/recipes/getRecipesByCategory.js
> +	if (!result || result.length === 0) {
тут погоджуюсь

2023-04-03 13:32 UTC, SergiiTernytskyi commented on src/controllers/recipes/getCategoryList.js
>  const { categories } = require("../../helpers");
так, справді, тому переніс в іншу папку, і я вирішив список категорій представити у вигляді масива, а не json,  як один із можливих рекомендацій ментора на плануванні

2023-04-03 13:34 UTC, SergiiTernytskyi commented on src/controllers/recipes/getCategoryList.js
> +		categories: categoryList,
погоджуюсь

2023-04-03 16:39 UTC, po4tovuj commented on src/controllers/recipes/getRecipesBySet.js
> +	const recipesLimit = Number(limit);
а взагалі краще винести це у або у хелпер, який буде робити всі необхідні перевірки що данні page та limit валідні, і повертати вже опрацьовані page i limit i offset. ти більше що перші тро строки будуть повторюватись на кількох пейджах і кількох роутах

2023-04-03 16:48 UTC, SergiiTernytskyi commented on src/service/recipes.js
>  	return await Recipe.findOne({ _id: recipeId });
findById виконується тим самим методом, тому швидшим бути не може https://github.com/Automattic/mongoose/blob/8cb0e355f75140bd4506a80b21dd94244f828cb0/lib/model.js#L1067-L1069

2023-04-03 16:49 UTC, SergiiTernytskyi commented on src/controllers/recipes/getRecipesByCategory.js
> +	// }
поки не можу,

2023-04-03 16:51 UTC, SergiiTernytskyi commented on src/controllers/recipes/getCategoryList.js
> +	const categoryList = [...categories].sort((a, b) => a.localeCompare(b));
яка різниця де саме відбувається сортування. На зараз є можливість закидувати інший масив без можливості пошкодити функціонал ендпофнта

2023-04-03 16:57 UTC, po4tovuj commented on src/controllers/recipes/getCategoryList.js
> +	const categoryList = [...categories].sort((a, b) => a.localeCompare(b));
насправді різниця, є бо якщо залишити так як ти зробив, то це треба буде повторювати всюди де будуть ці данні використовуваться. ок хочеш залишити так залишай. я висловив свою думку.

2023-04-03 17:03 UTC, po4tovuj approved these changes

2023-04-03 17:03 UTC, po4tovuj commented on src/controllers/recipes/getRecipesBySet.js
> +	const recipesLimit = Number(limit);
я не кажу виправляти щось, я кажу що ці маніпуляції будуть повторюватись в кількох місцях і краще цей шматок винести в окремий метод. Знову ж таки щоб притримуватись правила DRY (don't repeat yourself)

2023-04-03 17:03 UTC, po4tovuj commented on src/controllers/recipes/getRecipesBySet.js
> +	const recipesLimit = Number(limit);
не хочеш виносити, як скажеш.

2023-04-03 18:06 UTC, SergiiTernytskyi commented on src/controllers/recipes/getRecipesBySet.js
> +	const recipesLimit = Number(limit);
виныс в окремі функції

2023-04-04 06:24 UTC, po4tovuj approved these changes

2023-04-04 08:27 UTC, merged